# ============================================
# APPLICATION
# ============================================

spring.application.name=API-GATEWAY

server.port=8080


# ============================================
# EUREKA
# ============================================

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost


# ============================================
# AUTH SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**


# ============================================
# USER SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/users/**


# ============================================
# DEPARTMENT SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[2].id=department-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://DEPARTMENT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/departments/**


# ============================================
# COLLEGE SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[3].id=college-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://COLLEGE-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/college/**


# ============================================
# MENTOR SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[4].id=mentor-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://MENTOR-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/mentors/**


# ============================================
# COMMUNITY SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[5].id=community-service
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://COMMUNITY-SERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/community/**


# ============================================
# CHAT SERVICE
# ============================================

spring.cloud.gateway.server.webmvc.routes[6].id=chat-service
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://CHAT-SERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/api/chat/**


# ============================================
# ACTUATOR
# ============================================

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,gateway

